### ISSUE TITLE
Incorrect doctors address

### ISSUE THREAD

**Issue by BojanKogoj** [sledilnik/zdravniki-data#11]
Some doctors fall under ZDRAVSTVENI DOM DR. ADOLFA DROLCA MARIBOR, however they actually work at different locations.

For example: https://www.zd-mb.si/Storitve/Zdravniki?id=13093#doctorAnchor
His location on the map: ULICA TALCEV 9
Actual location: Zagrebška cesta 84a

Any way to get that additional information, since it's not in xlsx?

**Comment by SterArcher** [comment]
I apologise in the name of the whole project for the late reply. We have not seen this issue until now. I have made the fix as it still was not reported by the usual pathway through the webpage. 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/29688990/201541262-739a4e34-a01c-4d4a-9c97-ce5cc7fd004d.png">

The problem currently is that there is no good source for accurate locations. You can read more on that in the recent manuscript presented: https://zenodo.org/record/7313431#.Y3FKbS0w01I

We are working with the stakeholders in Slovenia to make data accuracy better. 

Thank you for opening this issue.
